#!/usr/bin/env node
/**
 * Collects every string still marked `{ "text": "…", "draft": true }` in the
 * data files and writes CONTENT-TODO.md — the owner's replacement list.
 * Runs from `npm run build`, before Eleventy. No dependencies on purpose.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const DATA_DIR = path.join(ROOT, "src", "_data");
const OUTPUT = path.join(ROOT, "CONTENT-TODO.md");

const SOURCES = [
  { file: "src/_data/content.en.json", label: "English", disk: "content.en.json" },
  { file: "src/_data/content.ar.json", label: "Arabic", disk: "content.ar.json" },
  { file: "src/_data/site.json", label: "Shared facts", disk: "site.json" },
];

/** Key path (without array indices) → one line saying what the owner must supply. */
const HINTS = [
  [/^hero\.subtitle$/, "One line under the hero title, 12-18 words."],
  [/^about\.body$/, "40-60 words about the place: what it feels like and why people stay."],
  [/^menu\.items\[\d+\]\.desc$/, "One short line about this item, up to 12 words."],
  [/^instagram\.items\[\d+\]\.href$/, "Permalink of this post (https://www.instagram.com/p/...)."],
  [/^site\.url$/, "Public address of the deployed site — used for canonical, hreflang and Open Graph."],
];

const IMAGE_KEYS = /(^|\.)(image)$/;

function hintFor(keyPath) {
  for (const [pattern, hint] of HINTS) {
    if (pattern.test(keyPath)) return hint;
  }
  return "Replace with the owner's own wording.";
}

function isDraftValue(value) {
  return (
    value !== null &&
    typeof value === "object" &&
    !Array.isArray(value) &&
    typeof value.text === "string" &&
    value.draft === true
  );
}

function walk(node, prefix, visit) {
  if (Array.isArray(node)) {
    node.forEach((item, i) => walk(item, `${prefix}[${i}]`, visit));
    return;
  }
  if (node === null || typeof node !== "object") return;
  for (const [key, value] of Object.entries(node)) {
    const keyPath = prefix ? `${prefix}.${key}` : key;
    if (isDraftValue(value)) visit(keyPath, value.text, "draft");
    else if (typeof value === "string" && IMAGE_KEYS.test(key)) visit(keyPath, value, "image");
    else walk(value, keyPath, visit);
  }
}

function escapeCell(text) {
  return String(text).replace(/\s+/g, " ").replace(/\|/g, "\\|").trim();
}

function readSource(source) {
  const file = path.join(DATA_DIR, source.disk);
  return JSON.parse(fs.readFileSync(file, "utf8"));
}

function main() {
  const drafts = [];
  const missingImages = new Map();

  for (const source of SOURCES) {
    const data = readSource(source);
    const prefix = source.disk === "site.json" ? "site" : "";
    walk(data, prefix, (keyPath, text, kind) => {
      if (kind === "draft") {
        drafts.push({ file: source.file, keyPath, text });
        return;
      }
      const onDisk = path.join(ROOT, "src", text);
      if (!fs.existsSync(onDisk) && !missingImages.has(text)) {
        missingImages.set(text, keyPath);
      }
    });
  }

  const lines = [];
  lines.push("# Content to write");
  lines.push("");
  lines.push(
    "Generated by `scripts/content-todo.js` on every `npm run build`. Do not edit by hand —"
  );
  lines.push(
    "edit the data files instead. A line disappears from this list the moment its"
  );
  lines.push("`\"draft\": true` flag is removed, and the amber badge disappears from the page with it.");
  lines.push("");

  if (drafts.length === 0) {
    lines.push("Nothing left to write: no string is marked as a draft.");
  } else {
    lines.push(`${drafts.length} strings are still placeholder text.`);
    lines.push("");
    for (const source of SOURCES) {
      const rows = drafts.filter((d) => d.file === source.file);
      if (rows.length === 0) continue;
      lines.push(`## ${source.label} — \`${source.file}\``);
      lines.push("");
      lines.push("| Key | Current text | What is needed |");
      lines.push("| --- | --- | --- |");
      for (const row of rows) {
        lines.push(
          `| \`${row.keyPath}\` | ${escapeCell(row.text)} | ${hintFor(row.keyPath)} |`
        );
      }
      lines.push("");
    }
  }

  if (missingImages.size > 0) {
    lines.push("## Photos still missing");
    lines.push("");
    lines.push(
      "Files named by the dictionaries that are not in `src/assets/images/` yet. Sections fall back to a branded tile."
    );
    lines.push("");
    lines.push("| File | First referenced by |");
    lines.push("| --- | --- |");
    for (const [file, keyPath] of missingImages) {
      lines.push(`| \`src/${file}\` | \`${keyPath}\` |`);
    }
    lines.push("");
  }

  lines.push("## Also worth knowing");
  lines.push("");
  lines.push(
    "- The nine Instagram tiles are a snapshot, not a live feed: they show the posts captured on the build date recorded in `site.capturedOn`. Refreshing them means replacing the files in `src/assets/images/instagram/` and the links in `instagram.items[]`."
  );
  lines.push("");

  fs.writeFileSync(OUTPUT, lines.join("\n"), "utf8");
  process.stdout.write(
    `content-todo: ${drafts.length} draft strings, ${missingImages.size} missing photos → CONTENT-TODO.md\n`
  );
}

main();
